import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar/NavBar";
import { Suspense } from "react";
import LoadingTerminal from "./loading";

const firaCode = Fira_Code({
  subsets: ["latin"],
  variable: "--font-fira-code",
});

export const metadata: Metadata = {
  title: "Leonardo Portfólio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={firaCode.variable}>
        <NavBar />
        <div className="container">
        <Suspense fallback={<LoadingTerminal />}>{children}</Suspense>
          {" "}
          {/* Container centralizado */}
        </div>
      </body>
    </html>
  );
}
